### PR TITLE
Enhanced Readme File

### LINKED ISSUE #3: Readme improvements
Add photos of the application and explain the features, you can also fix any grammatical mistakes

### PR DESCRIPTION
**Pull request by thatguywhocode**
closes #3 
I have improved readme file.

### CODE REVIEW

**Comment by Priyanshi662** [comment]
please change the name to discussion forum, also the screenshot should be of the application.

**Comment by thatguywhocode** [comment]
Check now @Priyanshi662

**Comment by Priyanshi662** [comment]
merged thanks for contributing!

**Comment by Priyanshi662** [comment]
@thatguywhocode  mention your name please

**Comment by thatguywhocode** [comment]
@Priyanshi662 Kanishk Bansal

**Pull request merged**
